{"46a278017f3323391c62ae8c2fbc99aa":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"eff498b04c3ad9fe","status":"broken","statusDetails":"`cy.visit()` must be called with a `url` or an `options` object containing a `url` as its 1st argument\n                \n                https://on.cypress.io/visit\n                \n                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `example to-do app`","time":{"start":1666187455553,"stop":1666187455735,"duration":182}}]}}